version: '3'
services:
 ubuntu-service:
  image: ubuntu-latest
  build: .
  volumes: 
   - /mnt/c/Users/BB/Desktop/docker-setup/projects/backend:/var/www/backend
   - /mnt/c/Users/BB/Desktop/docker-setup/projects/frontend:/var/www/frontend
  ports:
   - 8080:8080
   - 80:80